-- ============================================================
-- ACÓLITOS — o que falta aplicar no banco
-- Atualizado em 18/08/2026.
--
-- NADA PENDENTE. Não há o que colar hoje.
--
-- Aplicado e conferido rodando (sem sessão, pela chave pública do site):
--   048_tarefas.sql                  — a tabela das Tarefas dos times
--   049_convocar_por_time.sql        — convocar evento por time da pastoral
--   050_tarefas_andamento.sql        — o estado "em andamento" e a lista de responsáveis
--   051_tarefas_recusa_sem_login.sql — a leitura recusa quem não fez login, como as irmãs
--
-- Quando houver migration nova, este arquivo volta a ter só o que ainda falta.
-- ============================================================
