-- ============================================================
-- ACÓLITOS — o que falta aplicar no banco
-- Atualizado em 18/08/2026.
--
-- NADA PENDENTE. Não há o que colar hoje.
--
-- Aplicado pelo dono em 18/08/2026:
--   048_tarefas.sql                    — a tabela das Tarefas dos times
--   049_convocar_por_time.sql          — convocar evento por time da pastoral
--   050_tarefas_andamento.sql          — o estado "em andamento" e a lista de responsáveis
--   051_tarefas_recusa_sem_login.sql   — a leitura recusa quem não fez login, como as irmãs
--   052_candidatura_confere_vaga.sql   — aprovar candidatura confere a vaga no servidor
--   053_responsaveis_sem_eh_equipe.sql — ser responsável exige só estar num time
--   054_tarefa_origem.sql              — a recorrente sabe de qual conclusão nasceu
--
-- Conferido de fora, sem sessão: `origem_id` existe (054), e as funções mexidas seguem
-- recusando quem não fez login. O COMPORTAMENTO da 052 e da 053 fica atrás de login e não
-- dá para medir daqui — para isso existe `docs/CONFERIR-NO-BANCO.sql`, que é só leitura.
--
-- Quando houver migration nova, este arquivo volta a ter só o que ainda falta.
-- ============================================================
